"""Remove housing prefs

Revision ID: ad3a2bc15388
Revises: 8f4e1d53b495
Create Date: 2022-03-21 16:31:31.012831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3a2bc15388'
down_revision = '8f4e1d53b495'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('applications_housing_pref_id_fkey', 'applications', type_='foreignkey')
    op.drop_column('applications', 'housing_pref_id')
    op.drop_table('housing_prefs')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('housing_pref_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('applications_housing_pref_id_fkey', 'applications', 'housing_prefs', ['housing_pref_id'], ['id'])
    op.create_table('housing_prefs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='housing_prefs_pkey')
    )
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

